Feat/data delivery to lims
Clinical-Genomics/cg pull request #1223
Opened 2021-07-02 09:04 UTC by patrikgrenfeldt

## Description
*This PR adds/fixes data delivery to the data exported to LIMS*

### How to prepare for test
- [ ] ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] paxa the environment: `paxa`
- [ ] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] do submit order

### Expected test outcome
- [ ] check that data delivery was set on the lims sample
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] ~Document in ...~
- [ ] create UDF Data Delivery in LIMS production
- [ ] Deploy this branch
- [ ] Inform to AG, data_analysis

2021-07-02 09:27 UTC, annagellerbring commented
FYI @emmser

2021-07-02 11:59 UTC, henrikstranneheim approved these changes
👍

2021-07-06 10:59 UTC, Mropat commented on cg/constants/lims.py
> -    "original_lab": "Original Lab",
this cannot be deleted

2021-07-06 11:01 UTC, Mropat requested changes
Approved to add new UDF, but dont delete the old ones that are needed.
Where is the code for parsing data delivery into lims?

2021-07-06 11:27 UTC, merged