refactor(refine pool refactoring)
Clinical-Genomics/cg pull request #1800
Opened 2023-03-15 10:44 UTC by ChrOertlin

## Description

Refinement of the initial pool refactoring

### Added

-

### Changed

-

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

2023-03-16 10:41 UTC, ChrOertlin commented on cg/server/api.py
> +    customer_objs: Optional[List[Customer]] = (
@henrikstranneheim
This is what we slacked about the other day. 

```Python
get_pools_for_customer()
```

had three function outcomes:
1. Return all pools
2. Return pools for customer
3. Return pools for customer where name or order match enquiry

I broke this function up into: 

```Python
get_pools_by_customer_id()
get_pools_by_name_enquiry()
get_pools_by_oder_enquiry()
```
Then I extracted the logic of constructing the end result into 
```servers/api.py```

I think this shows a bit better what is going on under the hood, but is still messy... 
Plus we have query functions that only filter on a single attribute.

I tested the functionality of this construction and it behaves identical to the previous implementation.

2023-03-16 13:56 UTC, ChrOertlin commented
1. Loads pools for all customers:
![image](https://user-images.githubusercontent.com/8860786/225639251-09540158-0fa3-4934-96fe-1b3776f980db.png)

2. Loads pools for one customer
![image](https://user-images.githubusercontent.com/8860786/225639480-13d7edb5-9f96-4abe-a7ed-20de63725b75.png)

3. Load pools for one customer and an enquiry
![image](https://user-images.githubusercontent.com/8860786/225639718-1357ea63-977e-4a49-9623-7dc2c941ceb0.png)

2023-03-16 14:52 UTC, diitaz93 requested changes
good job 👍

2023-03-16 14:52 UTC, diitaz93 commented on tests/store/api/test_find_business_data.py
> +    assert len(pools) == EXPECT_ONE_POOL
Maybe separate this function into 4 different tests

2023-03-16 14:52 UTC, diitaz93 commented on tests/store/filters/test_status_pool_filters.py
> +    # ASSERT that the query is a Query
```suggestion
    # THEN a Query is returned
```

2023-03-16 14:52 UTC, diitaz93 commented on tests/store/filters/test_status_pool_filters.py
> +    # ASSERT that the query is a Query
```suggestion
    # THEN a Query is returned
```

2023-03-16 14:52 UTC, diitaz93 commented on tests/store/filters/test_status_pool_filters.py
> +    assert pools.all() and len(pools.all()) == 2 and pools.all()[0].name == name
I think this makes it easier to determine the statement that failed
```suggestion
    assert pools.all()
    assert len(pools.all()) == 2
    assert pools.all()[0].name == name
```

2023-03-16 14:52 UTC, diitaz93 commented on tests/store/filters/test_status_pool_filters.py
> +    assert pools.all() and len(pools.all()) == 1 and pools.all()[0].name == name
easier to debug
```suggestion
    assert pools.all()
    assert len(pools.all()) == 1
    assert pools.all()[0].name == name
```

2023-03-16 14:52 UTC, diitaz93 commented on tests/store/filters/test_status_pool_filters.py
> +    assert pools.all() and len(pools.all()) == 1 and pools.all()[0].name == name
also the fixtures could be used here instead of 1 if you consider it appropiate

2023-03-16 14:52 UTC, diitaz93 commented on tests/store/filters/test_status_pool_filters.py
> +    assert pools.all() and len(pools.all()) == 1 and pools.all()[0].name == name
easier to debug
```suggestion
    assert pools.all()
    assert len(pools.all()) == 1
    assert pools.all()[0].name == name
```

2023-03-16 14:52 UTC, diitaz93 commented on tests/store/filters/test_status_pool_filters.py
>      assert pools.all() and len(pools.all()) == 1
see THEN statements below and maybe implement this structure in the tests above

2023-03-16 15:03 UTC, henrikstranneheim approved these changes
Great! 👍

2023-03-16 15:03 UTC, henrikstranneheim commented on tests/store/api/test_find_business_data.py
> +    # THEN two pools should be returned
```suggestion
    # THEN one pool should be returned
```

2023-03-16 15:03 UTC, henrikstranneheim commented on tests/store/api/test_find_business_data.py
> +    # THEN two pools should be returned
```suggestion
    # THEN one pool should be returned
```

2023-03-16 15:03 UTC, henrikstranneheim commented on tests/store/api/test_find_business_data.py
> +    # WHEN fetching pools by customer id
```suggestion
    # WHEN getting pools by customer id
```

2023-03-16 15:15 UTC, diitaz93 commented on cg/store/api/find_business_data.py
Is weird this diff but it seems that the only difference are some extra functions added in the middle of the script

2023-03-16 15:26 UTC, ChrOertlin commented on tests/meta/orders/test_meta_orders_status.py
>      assert new_pool.name == "pool-2"
Yes, this meta test thing deserves its own pr :)

2023-03-16 15:31 UTC, ChrOertlin commented on cg/server/api.py
> +    pools_q: List[Pool] = db.get_pools_to_render(
Yes, I believe this is what it means

2023-03-17 08:15 UTC, ChrOertlin commented on cg/store/api/find_business_data.py
I wanted to put

```Python
data: List[Dict] = [pool_obj.to_dict() for pool_obj in pools_q[:30]]
```
into a common function, just to realise that all models have their own `to_dict()` function, so I abandoned it. Maybe it is a remnant of that

2023-03-17 08:22 UTC, diitaz93 approved these changes
👍

2023-03-17 08:39 UTC, merged

2023-03-17 08:49 UTC, ChrOertlin commented
Stage:
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/hiseq.clinical
done.
Log deploy... done.
cg, version 27.1.2

Production:
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/hiseq.clinical
done.
Log deploy... done.
cg, version 27.1.2