refine_refactor_invoice
Clinical-Genomics/cg pull request #1810
Opened 2023-03-16 14:29 UTC by ChrOertlin

## Description

### Added

- Tests for invoice model

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do make sure tests run

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

2023-03-16 15:13 UTC, diitaz93 requested changes
👍

2023-03-16 15:13 UTC, diitaz93 commented on tests/store/api/test_find_business_data.py
> +    assert invoice and invoice.id == 1
```suggestion
    assert isinstance(invoice,Invoice)
    assert invoice.id == 1
```

2023-03-17 08:27 UTC, diitaz93 approved these changes
👍

2023-03-17 09:10 UTC, ChrOertlin commented
1. Can retrieve invoice using entry id:
![image](https://user-images.githubusercontent.com/8860786/225861277-bc2da803-a4f7-434e-8612-5045cf5e79f7.png)

2. Can create new invoice entry 2023-03-17
![image](https://user-images.githubusercontent.com/8860786/225861702-e81ce4aa-2788-4b54-b11a-d680344829eb.png)

2023-03-17 09:17 UTC, merged