Remove unused fixtures
Clinical-Genomics/cg pull request #2053
Opened 2023-05-23 16:13 UTC by seallard

## Description

### Added

-

### Changed

-

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b [THIS-BRANCH-NAME] -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

2023-05-23 16:18 UTC, diitaz93 requested changes
Please leave the demultiplex fixtures as I am using them in my PR. If they remain unused I will remove them myself :)

2023-05-23 16:51 UTC, seallard commented
@diitaz93 Can you check if there are any additional fixtures that you need that I've removed?

2023-05-24 06:41 UTC, diitaz93 approved these changes
Looks good on my side 👍 Great initiative

2023-05-24 06:41 UTC, diitaz93 commented on tests/store/conftest.py
> -    return Path(fixtures_dir, "store", "api", "application_versions.xlsx").as_posix()
If this file is not used maybe you could consider removing it too

2023-05-24 06:41 UTC, diitaz93 commented on tests/store/conftest.py
> -    return Path(fixtures_dir, "store", "api", "applications.xlsx").as_posix()
same here

2023-05-24 06:41 UTC, diitaz93 commented on tests/conftest.py
> -    return dragen_flow_cell.id
I would like you to leave this one too 🙂

2023-05-24 06:55 UTC, seallard commented
@diitaz93 Thanks for checking! Nice 😄

2023-05-24 08:02 UTC, merged