Add tower to run workflow
Clinical-Genomics/cg pull request #2357
Opened 2023-08-23 09:51 UTC by sofstam

## Description
This PR adds tower option to cg workflow taxprofiler run
Open [PR](https://github.com/Clinical-Genomics/servers/pull/1098) in servers

### Added

- 

### Changed

-

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_main -t cg -b taxprofiler_run_tower -a
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

2023-08-25 12:35 UTC, sofstam commented
There is a code smell regarding the `run command` and the 13 authorized arguments. I have not solved it yet but otherwise it is ready for review :)

2023-08-25 12:49 UTC, fevac requested changes
Nicee!! 🌟 just minor comments from my side

2023-08-25 12:49 UTC, fevac commented on cg/models/cg_config.py
> +    tower_pipeline: str
Not for this PR but we need to finish refactoring the tower and nextflow classes and the cg config file in servers so this is not duplicated.

2023-08-25 12:49 UTC, fevac commented on cg/cli/workflow/taxprofiler/base.py
> +    if not dry_run:
Currently we only interact with trailblazer for tower analyses (not when using nextflow). We should make sure that every we interact with trailblazer we only do it when using tower something like:
```suggestion
    if not dry_run and with_tower:
```
Similar when accessing the tower_id for re- runs. I believe this is currently not handled in rnafusion. 
Could you test your branch for running taxprofiler with nextflow from-start and with resume, just to make sure we are handling those?

2023-08-25 12:49 UTC, fevac commented on tests/cli/workflow/taxprofiler/test_cli_taxprofiler_run.py
> +    # GIVEN case-id
```suggestion
    # GIVEN  a valid case
```

2023-08-25 12:49 UTC, fevac commented on tests/cli/workflow/taxprofiler/test_cli_taxprofiler_run.py
> +    for message in [
do we want to test all default parameters?

2023-08-30 09:22 UTC, diitaz93 reviewed
Not an expert in the topic but looks good to me 😃

2023-08-31 07:59 UTC, fevac requested changes
nice! 🌟  good catch with the trailblazer logic. Some few additional comments

2023-08-31 07:59 UTC, fevac commented on cg/cli/workflow/taxprofiler/base.py
> +@OPTION_TOWER
let's remove this option. It's confusing and when we are using nextflow we do not want to use tower

2023-08-31 07:59 UTC, fevac commented on cg/cli/workflow/taxprofiler/base.py
> +    with_tower: bool,
remove option

2023-08-31 07:59 UTC, fevac commented on cg/cli/workflow/taxprofiler/base.py
> +    if not dry_run and not use_nextflow:
nice! 🌟

2023-08-31 14:28 UTC, sofstam commented
@fevac I have adressed your comments now.

2023-09-04 07:11 UTC, fevac approved these changes
🚀 💯

2023-09-04 08:39 UTC, sofstam commented
I will merge and deploy.

2023-09-04 08:44 UTC, fevac commented
it seems you need an approval from sysdev. @diitaz93 do you have time for it?

2023-09-04 11:44 UTC, diitaz93 approved these changes
👍

2023-09-04 12:25 UTC, merged

2023-09-04 12:30 UTC, sofstam commented
Deploy on stage:
<img width="545" alt="Screenshot 2023-09-04 at 14 29 59" src="https://github.com/Clinical-Genomics/cg/assets/91951607/faf7a065-8653-45de-934c-147af365dff1">

2023-09-04 12:33 UTC, sofstam commented
Deploy on production:
<img width="519" alt="Screenshot 2023-09-04 at 14 33 29" src="https://github.com/Clinical-Genomics/cg/assets/91951607/63818893-f016-4658-8814-0be66b9714cd">