fix(rm_format_tags): Do not propagate deliverables format tags into HK
Clinical-Genomics/cg pull request #711
Opened 2020-08-18 13:28 UTC by henrikstranneheim

This PR fixes:

- Removes the propagation of format tags from the deliverable file into HK
- Adds a test

### How to prepare for test
- [ ] ssh to hasta (depending on type of change)
- [ ] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh remove_format_tags`

### How to test
- [ ] login to hasta
- [ ] do ´us´
- [ ] Check that the current bundle for toughmarten has tag `bam` together with the `bam-mt` tag
1. `housekeeper delete bundle toughmarten`

### Expected test outcome
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

2020-08-18 13:34 UTC, henrikstranneheim commented
Strongbison bundle in HK using master:
<img width="1398" alt="Screenshot 2020-08-18 at 15 29 19" src="https://user-images.githubusercontent.com/584738/90518872-97083500-e167-11ea-9090-4a9c9a970b4e.png">

Strongbison bundle using this branch:
<img width="1398" alt="Screenshot 2020-08-18 at 15 34 42" src="https://user-images.githubusercontent.com/584738/90519478-59f07280-e168-11ea-8390-20de4b27c9ed.png">

2020-08-19 06:52 UTC, moonso requested changes
Ok we had some discussions

2020-08-19 06:52 UTC, moonso commented on cg/meta/store/base.py
>  ) -> list:
```suggestion
) -> List[str]:
```

2020-08-19 06:59 UTC, henrikstranneheim commented on cg/meta/store/base.py
>  ) -> list:
Done

2020-08-19 07:46 UTC, moonso approved these changes

2020-08-19 07:46 UTC, moonso commented
Well done!

2020-08-19 10:28 UTC, henrikstranneheim commented
@moonso Would you like to M&D?

2020-08-19 12:02 UTC, merged

2020-08-19 12:12 UTC, henrikstranneheim commented
Deployed on Hasta:
![Screenshot 2020-08-19 at 14 12 10](https://user-images.githubusercontent.com/584738/90633241-faf13300-e225-11ea-8508-6d0f141510e9.png)