DRAFT: refactor microSALT to use case_id
Clinical-Genomics/cg pull request #895
Opened 2020-12-16 17:31 UTC by Mropat

This PR adds/fixes ...

### How to prepare for test
- [ ] ssh to hasta (depending on type of change)
- [ ] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-cg-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] login to ...
- [ ] do ...

### Expected test outcome
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

2020-12-30 09:43 UTC, Mropat commented
cg workflow micrisalt start bigdrum works as intended
![image](https://user-images.githubusercontent.com/35531751/103343203-d5a1ea80-4a8b-11eb-95c6-659a30204bd1.png)

2020-12-30 10:46 UTC, Mropat commented
Successfully starts whole workflow for one sample only 
![image](https://user-images.githubusercontent.com/35531751/103346584-b22f6d80-4a94-11eb-9a34-e148444a6e19.png)

2020-12-30 10:50 UTC, Mropat commented
Starting bigdrum with ticket id works as intended
![image](https://user-images.githubusercontent.com/35531751/103346734-3124a600-4a95-11eb-97d5-28c766d5942c.png)

2021-01-07 10:20 UTC, barrystokman commented
`store-available` was not working correctly due to the field `action` to being set correctly. Should we 1) test that here too and 2) fix the existing microsalt 'families' in the database?

2021-01-07 11:26 UTC, Mropat commented
@barrystokman store-available was not working because production was not starting analyses through cg. Instead, they would use cg to make config, and then ran microsalt manually with the config as input argument. This means that the code which would set family action to running was never invoked.
Now I have tested starting the whole workflow through cg, and it workd (which will set the action properly). So the store-available can now catch those cases without changing families query

2021-01-07 13:54 UTC, barrystokman approved these changes
Looks good to me!

2021-01-08 10:40 UTC, Mropat commented
Storing in HK works again with Hermes in place.
Kicks out non existing files and stores bundle

![image](https://user-images.githubusercontent.com/35531751/104006057-4a6cd700-51a6-11eb-9fca-2d78b63826ce.png)

2021-01-11 09:03 UTC, moonso requested changes
Wow great job! Some minor comments

2021-01-11 09:03 UTC, moonso commented on tests/cli/workflow/microsalt/conftest.py
> +            hermes_api=HermesApi(
Could this be made as a common fixture?

2021-01-11 09:03 UTC, moonso commented on tests/cli/workflow/microsalt/test_microsalt_case_config.py
> +    ticket = "123000"
Convert this to fixture?

2021-01-11 10:05 UTC, Mropat commented on cg/apps/hermes/models.py
> +    @validator("files", each_item=True)
What a coincidence, I was inspired by Hermes validators to do this :laughing:

2021-01-11 12:37 UTC, moonso approved these changes

2021-01-11 12:51 UTC, merged

2021-01-11 14:42 UTC, Mropat commented
Deployed on hasta:
![image](https://user-images.githubusercontent.com/35531751/104196070-a98b4f80-5423-11eb-9257-3427a07d70e6.png)